// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftvenrJBW35mt_rbYdaRVMVSmuebeBDA',
    appId: '1:635509198111:android:4e562e0352929cb3b0342a',
    messagingSenderId: '635509198111',
    projectId: 'newcrudeproject',
    storageBucket: 'newcrudeproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHLBCeC3OWUS-avZ_AymVn0W1TiAmab3M',
    appId: '1:635509198111:ios:8bce5c4d4a148d90b0342a',
    messagingSenderId: '635509198111',
    projectId: 'newcrudeproject',
    storageBucket: 'newcrudeproject.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebaseFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBnUsPMpfBa_Ze2A7r9TOTFf1kGAi-4Iw',
    appId: '1:635509198111:web:79e1e1bb8b95f8d6b0342a',
    messagingSenderId: '635509198111',
    projectId: 'newcrudeproject',
    authDomain: 'newcrudeproject.firebaseapp.com',
    storageBucket: 'newcrudeproject.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHLBCeC3OWUS-avZ_AymVn0W1TiAmab3M',
    appId: '1:635509198111:ios:8bce5c4d4a148d90b0342a',
    messagingSenderId: '635509198111',
    projectId: 'newcrudeproject',
    storageBucket: 'newcrudeproject.firebasestorage.app',
    iosBundleId: 'com.example.crudfirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBnUsPMpfBa_Ze2A7r9TOTFf1kGAi-4Iw',
    appId: '1:635509198111:web:bc63a0bd6e206968b0342a',
    messagingSenderId: '635509198111',
    projectId: 'newcrudeproject',
    authDomain: 'newcrudeproject.firebaseapp.com',
    storageBucket: 'newcrudeproject.firebasestorage.app',
  );

}